server:
  port: 40201
  shutdown: graceful

spring:
  profiles:
    active: ${profileActive:dev}
  main:
    allow-bean-definition-overriding: true
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: appspaces-app
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

mybatis:
  mapper-locations: classpath:com/appspaces/boot/**/repository/*.xml
  configuration:
    use-actual-param-name: true
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.appspaces: info
